spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/confort?stringtype=unspecified
    username: cristian
    password: clancy242005
    driverClassName: org.postgresql.Driver
