spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 60000
  mail:
    host: smtp.gmail.com
    port: 587
    username: tapiceria.confort24@gmail.com
    password: bjwnkfaqdwqhpmeu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true