spring:
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: none
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 60000

backup:
  dir: C:/Users/crist/Documents/SENA/TAPICERIA CONFORT/Copia_seguridad

postgres:
  user: cristian
  password: clancy242005
  db: confort
  host: localhost
  port: 5432
  pgDumpPath: "C:/Program Files/PostgreSQL/17/bin/pg_dump.exe"
  psqlPath: "C:/Program Files/PostgreSQL/17/bin/psql.exe"
