spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/confort?stringtype=unspecified
    username: postgres
    password: 12345
    driverClassName: org.postgresql.Driver